//! PDF report export for Rushes Log.
//!
//! Uses `genpdf` to generate professional PDF reports with:
//! - Header: DIT Pro + shoot date + generation time
//! - Summary section: total reels, clips, size, cameras
//! - Data table with all rushes log entries
//! - Signature area for DIT sign-off
//! - Footer: "Generated by DIT Pro"

use anyhow::{Context, Result};
use genpdf::elements::{Break, LinearLayout, Paragraph, TableLayout};
use genpdf::fonts::{FontData, FontFamily};
use genpdf::style::{self, Style};
use genpdf::{Alignment, Element};
use std::path::Path;

use super::{format_bytes, format_duration, RushesLogReport};

/// Try to load a font from common macOS/Linux locations.
/// Returns a FontFamily suitable for genpdf Document creation.
fn load_font_family() -> Result<FontFamily<FontData>> {
    // macOS: Arial files in /System/Library/Fonts/Supplemental/
    let mac_supp = Path::new("/System/Library/Fonts/Supplemental");
    if mac_supp.exists() {
        let regular = mac_supp.join("Arial.ttf");
        let bold = mac_supp.join("Arial Bold.ttf");
        let italic = mac_supp.join("Arial Italic.ttf");
        let bold_italic = mac_supp.join("Arial Bold Italic.ttf");

        if regular.exists() && bold.exists() {
            let r = FontData::load(&regular, None)?;
            let b = FontData::load(&bold, None)?;
            let i = if italic.exists() {
                FontData::load(&italic, None)?
            } else {
                FontData::load(&regular, None)?
            };
            let bi = if bold_italic.exists() {
                FontData::load(&bold_italic, None)?
            } else {
                FontData::load(&bold, None)?
            };
            return Ok(FontFamily {
                regular: r,
                bold: b,
                italic: i,
                bold_italic: bi,
            });
        }
    }

    // Linux: Liberation Sans
    let linux_paths = [
        "/usr/share/fonts/truetype/liberation",
        "/usr/share/fonts/liberation-sans",
    ];
    for dir in linux_paths {
        let p = Path::new(dir);
        if p.exists() {
            if let Ok(family) = genpdf::fonts::from_files(p, "LiberationSans", None) {
                return Ok(family);
            }
        }
    }

    anyhow::bail!("No suitable font found for PDF generation")
}

/// Export a rushes log report to a PDF file.
pub fn export_pdf(report: &RushesLogReport, output_path: &Path) -> Result<String> {
    let font_family =
        load_font_family().context("Cannot generate PDF: no suitable font found on this system")?;

    let mut doc = genpdf::Document::new(font_family);
    doc.set_title(format!("Rushes Log — {}", report.shoot_date));

    let mut decorator = genpdf::SimplePageDecorator::new();
    decorator.set_margins(15);
    doc.set_page_decorator(decorator);

    // ── Title ──
    doc.push(
        Paragraph::new("DIT Pro — Rushes Log")
            .aligned(Alignment::Center)
            .styled(Style::new().bold().with_font_size(18)),
    );
    doc.push(
        Paragraph::new(format!("Shoot Date: {}", report.shoot_date))
            .aligned(Alignment::Center)
            .styled(Style::new().with_font_size(12)),
    );
    doc.push(
        Paragraph::new(format!("Generated: {}", report.generated_at))
            .aligned(Alignment::Center)
            .styled(
                Style::new()
                    .with_font_size(9)
                    .with_color(style::Color::Rgb(128, 128, 128)),
            ),
    );
    doc.push(Break::new(1.0));

    // ── Summary ──
    doc.push(Paragraph::new("Summary").styled(Style::new().bold().with_font_size(14)));

    let mut summary_layout = LinearLayout::vertical();
    summary_layout.push(
        Paragraph::new(format!(
            "Total Reels: {}   |   Total Clips: {}   |   Total Size: {}",
            report.summary.total_reels,
            report.summary.total_clips,
            format_bytes(report.summary.total_size),
        ))
        .styled(Style::new().with_font_size(10)),
    );

    if !report.summary.cameras_used.is_empty() {
        summary_layout.push(
            Paragraph::new(format!(
                "Cameras Used: {}",
                report.summary.cameras_used.join(", "),
            ))
            .styled(Style::new().with_font_size(10)),
        );
    }

    summary_layout.push(
        Paragraph::new(format!(
            "Total Duration: {}",
            format_duration(report.summary.total_duration_seconds),
        ))
        .styled(Style::new().with_font_size(10)),
    );

    doc.push(summary_layout);
    doc.push(Break::new(0.5));

    // ── Data Table ──
    // Column weights: Thumb, Reel, Camera, Clips, Size, Dur, Speed, Status, MHL, Proxy, Res, Codec, FPS
    let mut table = TableLayout::new(vec![2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]);

    // Header row
    let header_style = Style::new().bold().with_font_size(8);
    let mut header_row = table.row();
    for header in [
        "Thumb",
        "Reel",
        "Camera",
        "Clips",
        "Size",
        "Duration",
        "Speed",
        "Status",
        "MHL",
        "Proxy",
        "Resolution",
        "Codec",
        "FPS",
    ] {
        header_row.push_element(Paragraph::new(header).styled(header_style));
    }
    header_row.push().context("Failed to push header row")?;

    // Data rows
    let cell_style = Style::new().with_font_size(7);
    let failed_style = Style::new()
        .with_font_size(7)
        .with_color(style::Color::Rgb(204, 0, 0));

    for entry in &report.entries {
        let is_failed = entry.backup_status == "Failed" || entry.failed_files > 0;
        let s = if is_failed { failed_style } else { cell_style };

        let camera = if entry.camera_model.is_empty() {
            entry.camera_brand.clone()
        } else {
            format!("{} {}", entry.camera_brand, entry.camera_model)
        };

        let mut row = table.row();

        // Thumbnail column
        if let Some(ref thumb_path) = entry.thumbnail_path {
            if Path::new(thumb_path).exists() {
                if let Ok(img) = genpdf::elements::Image::from_path(thumb_path) {
                    row.push_element(img.with_alignment(Alignment::Center));
                } else {
                    row.push_element(Paragraph::new("-"));
                }
            } else {
                row.push_element(Paragraph::new("-"));
            }
        } else {
            row.push_element(Paragraph::new("-"));
        }

        row.push_element(Paragraph::new(&entry.reel_name).styled(s));
        row.push_element(Paragraph::new(&camera).styled(s));
        row.push_element(Paragraph::new(entry.clip_count.to_string()).styled(s));
        row.push_element(Paragraph::new(format_bytes(entry.total_size)).styled(s));
        row.push_element(Paragraph::new(format_duration(entry.duration_seconds)).styled(s));
        row.push_element(Paragraph::new(format!("{:.1} MB/s", entry.avg_speed_mbps)).styled(s));
        row.push_element(Paragraph::new(&entry.backup_status).styled(s));
        row.push_element(Paragraph::new(if entry.mhl_verified { "Yes" } else { "No" }).styled(s));
        row.push_element(Paragraph::new(&entry.proxy_status).styled(s));
        row.push_element(Paragraph::new(entry.resolution.as_deref().unwrap_or("-")).styled(s));
        row.push_element(Paragraph::new(entry.codec.as_deref().unwrap_or("-")).styled(s));
        row.push_element(Paragraph::new(entry.frame_rate.as_deref().unwrap_or("-")).styled(s));
        row.push().context("Failed to push data row")?;
    }

    doc.push(table);
    doc.push(Break::new(1.5));

    // ── Signature Area ──
    doc.push(Paragraph::new("Sign-Off").styled(Style::new().bold().with_font_size(12)));
    doc.push(Break::new(0.5));

    let mut sig_layout = LinearLayout::vertical();
    sig_layout.push(
        Paragraph::new("DIT Name: _________________________________     Date: ____________")
            .styled(Style::new().with_font_size(10)),
    );
    sig_layout.push(Break::new(1.0));
    sig_layout.push(
        Paragraph::new("Signature:  _________________________________")
            .styled(Style::new().with_font_size(10)),
    );
    sig_layout.push(Break::new(1.0));
    sig_layout.push(
        Paragraph::new("Notes: _______________________________________________________________")
            .styled(Style::new().with_font_size(10)),
    );
    doc.push(sig_layout);

    doc.push(Break::new(1.0));

    // ── Footer ──
    doc.push(
        Paragraph::new("Generated by DIT Pro — Professional Card Offload Engine")
            .aligned(Alignment::Center)
            .styled(
                Style::new()
                    .with_font_size(8)
                    .with_color(style::Color::Rgb(128, 128, 128)),
            ),
    );

    // Render to file
    doc.render_to_file(output_path)
        .with_context(|| format!("Failed to render PDF to {:?}", output_path))?;

    Ok(output_path.to_string_lossy().to_string())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::rushes_log::{RushesLogEntry, RushesLogReport, RushesLogSummary};

    #[test]
    fn test_export_pdf_basic() {
        let report = RushesLogReport {
            generated_at: "2026-03-09 10:00:00".to_string(),
            shoot_date: "2026-03-09".to_string(),
            entries: vec![RushesLogEntry {
                job_id: "j1".to_string(),
                job_name: "Test".to_string(),
                reel_name: "A001".to_string(),
                camera_brand: "ARRI".to_string(),
                camera_model: "ALEXA Mini".to_string(),
                clip_count: 10,
                first_clip: "A001C001.ari".to_string(),
                last_clip: "A001C010.ari".to_string(),
                source_path: "/Volumes/CARD".to_string(),
                total_size: 10_737_418_240,
                total_files: 10,
                completed_files: 10,
                failed_files: 0,
                duration_seconds: 300.0,
                avg_speed_mbps: 34.1,
                backup_status: "Verified".to_string(),
                mhl_verified: true,
                proxy_status: "None".to_string(),
                dest_paths: vec!["/Volumes/SSD1".to_string()],
                started_at: "2026-03-09 09:00:00".to_string(),
                completed_at: "2026-03-09 09:05:00".to_string(),
                resolution: Some("4096x2160".to_string()),
                frame_rate: Some("23.976".to_string()),
                codec: Some("Apple ProRes".to_string()),
                color_space: Some("bt709".to_string()),
                timecode_range: Some("01:00:00:00".to_string()),
                thumbnail_path: None,
            }],
            summary: RushesLogSummary {
                total_reels: 1,
                total_clips: 10,
                total_size: 10_737_418_240,
                total_duration_seconds: 300.0,
                cameras_used: vec!["ARRI".to_string()],
            },
        };

        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("test.pdf");

        // This test may fail in CI where fonts are not available
        match export_pdf(&report, &path) {
            Ok(_) => {
                assert!(path.exists());
                assert!(std::fs::metadata(&path).unwrap().len() > 0);
            }
            Err(e) => {
                // Expected on systems without Arial/Liberation fonts
                let msg = e.to_string();
                assert!(
                    msg.contains("font") || msg.contains("Font"),
                    "Unexpected error: {}",
                    msg
                );
            }
        }
    }
}
